HARDPOINTS: '2026'
SIM_STEPS:  330     # Number of steps for sweeping sim
LIVE_UPDATE: True   # Update the plots as sim steps are solved
SIMULATION: 'wheel_attitude'  # 'wheel_attitude', 'jacking'

HALF: 'front'        # 'front' or 'rear'
SIDE: 'right'       # 'left' or 'right'

TRAVEL:
  ENABLE:   True    # True to use MIN/MAX. False to use VALUE.
  VALUE:    0       # [mm] A value to fix the TRAVEL to during sim
  MIN:      -90     # [mm] Min range to sweep TRAVEL through during sim 
  MAX:      240     # [mm] Max for range to sweep TRAVEL through during sim

STEER: 
  ENABLE:   False   # True to use MIN/MAX. False to use VALUE.
  VALUE:    0       # [mm] A value to fix the STEER to during sim
  MIN:      -40     # [mm] Min for range to sweep STEER through during sim
  MAX:      40      # [mm] Max for range to sweep STEER through during sim

PLOTS:
  3D:           True
  CAMBER:       True
  TOE:          True
  CASTER:       True
  AXLE_PLUNGE:  True
  AXLE_ANGLES:  True