HARDPOINTS: '2026'
SIM_STEPS:  330            # Number of steps for sweeping sim
SIMULATION: 'travel'    # 'steer', 'steer_travel', 'travel', 'ackermann'

HALF: 'front' # 'front' or 'rear'
SIDE: 'right' # 'left' or 'right'

TRAVEL:
  MIN: -90  # [mm] Min range to sweep TRAVEL through during sim 
  MAX:  240 # [mm] Max for range to sweep TRAVEL through during sim

STEER: 
  MIN: -40 # [mm] Min for range to sweep STEER through during sim
  MAX:  40 # [mm] Max for range to sweep STEER through during sim