# GLOBAL OPTIMIZER
POP_SIZE: 35
N_OFFSPRINGS: 25
MAX_GEN: 25
M_PROB: 1.0
M_ETA: 15

# OPTIMIZATION TO RUN
OBJECTIVES: 
  - MinimumBumpSteer
  - ParallelSteer
  - NoCollision

# PARAMETERS TO OPTIMIZE
FREE_POINTS: 
  "tie_rod_inboard":
    x: [-50.0, 10.0]
    y: [-50.0, 50.0]
    z: [-40.0, 45.0]
  "tie_rod_outboard":
    x: [-20.0, 15.0]
    y: [-50.0, 50.0]
    z: [-50.0, 50.0]