# GLOBAL OPTIMIZER
POP_SIZE: 75
N_OFFSPRINGS: 40
MAX_GEN: 60

# OPTIMIZATION TO RUN
OBJECTIVES: 
  - MinimumBumpSteer
  - ParallelSteer

# PARAMETERS TO OPTIMIZE
FREE_POINTS: 
  "tr_ib":
    x: [-50.0, 50.0]
    y: [-20.0, 20.0]
    z: [-50.0, 50.0]
  "tr_ob":
    x: [-40.0, 40.0]
    y: [-20.0, 5.0]
    z: [-60.0, 0.0]