# 2026 hardpoints - 2025-09-13

baja_2026:
  shock_min: 327.025
  shock_max: 504.825
  wheel_radius: 300 # ~23in diameter
  wheel_width: 200 # ~8in width

  front:
    _type: 'DoubleAArm'

    # inboard a arm points
    upper_a_arm_front: [0.000, 220.000, 577.451]
    upper_a_arm_rear:  [377.031, 220.000, 488.638]
    lower_a_arm_front: [129.406, 190.000, 405.748]
    lower_a_arm_rear:  [430.861, 190.000, 335.364]

    # upright joints
    upper_ball_joint: [280.500, 623.594, 380.887]
    lower_ball_joint: [265.000, 652.000, 205.000]

    # steering_points
    tie_rod_inboard:  [156.823, 229.000, 500.000]
    tie_rod_outboard: [204.600, 643.423, 352.461]

    # shock points
    shock_location: "lower"
    shock_inboard:  [423.030, 270.000, 760.497]
    shock_outboard: [336.606, 457.657, 340.241]

    # axle pivot points
    pivot_inboard:  [277.000, 115.000, 430.265]
    pivot_outboard: [275.000, 579.302, 300.377]

    # wheel points
    wheel_center:  [275.000, 695.000, 305.066]

  rear:
    _type: 'SemiTrailingLink'

    # trailing link point
    trailing_link_front: [1230.000, 288.473, 351.437]

    # camber link points
    upper_camber_link_inboard:  [1877.000, 60.000, 424.981]
    upper_camber_link_outboard: [1783.278, 535.300, 350.603]
    lower_camber_link_inboard:  [1877.000, 60.000, 354.981]
    lower_camber_link_outboard: [1774.107, 535.300, 251.112]

    # shock points
    shock_location: "lower"
    shock_inboard:  [1696.652, 254.060, 756.518]
    shock_outboard: [1732.635, 499.091, 378.470]

    # axle pivot points
    pivot_inboard:  [1730.000, 54.408, 431.681]
    pivot_outboard: [1730.000, 467.300, 305.304]

    # wheel points
    wheel_center: [1730.000, 620.000, 305.304]